Feature/dockerize app and add migrations
AlekseyYuriev/questions-and-answers-api pull request #1
Opened 2024-11-27 15:06 UTC by AlekseyYuriev

2024-11-29 09:21 UTC, MishaShatilo requested changes
Молодец, хорошо постарался, единственное пересмотри еще раз entity, потому что где то софт делит есть где то нету, где то каскад есть где то нету, не знаю думал ли ты об этом вообще когда делал, но можешь подумать как бы ты хотел чтобы это было и чтобы было удобно работать, комменты оставил можно фиксить

2024-11-29 09:21 UTC, MishaShatilo commented on Dockerfile
> +CMD ["npm", "run", "start:dev"]
Давай сделаем multi stage докер файл первый стейдж будет билдить наше приложение а второй его ранить без привелигированных прав через node dist/main.js

2024-11-29 09:21 UTC, MishaShatilo commented on docker-compose.yml
> +      - PORT=${API_PORT}
можно создать отдельный файл энвов под докер и его прокидывать

2024-11-29 09:21 UTC, MishaShatilo commented on docker-compose.yml
> +      - postgres_db
можно еще хелсчеки сделать если интересно (https://docs.docker.com/compose/how-tos/startup-order/)

2024-11-29 09:21 UTC, MishaShatilo commented on src/answers/answer.entity.ts
> +  id: number;
Давай сделаем id:string и это будет uuid @PrimaryGeneratedColumn("uuid")

2024-11-29 09:21 UTC, MishaShatilo commented on src/answers/answer.entity.ts
> +    eager: true,
Думаю нам пока что не нужно сразу доставать авторов под вопросы всегда, можем повременить с этим

2024-11-29 09:21 UTC, MishaShatilo commented on src/answers/answers.controller.ts
> +  })
Нужно будет еще добавить описание body которое приходит, ошибки которые может вернуть эндпоинт и сам ответ который он будет возвращать

2024-11-29 09:21 UTC, MishaShatilo commented on src/answers/dtos/create-answer.dto.ts
> +    example: 'Try to change the connection port',
type еще можно указать

2024-11-29 09:21 UTC, MishaShatilo commented on src/app.module.ts
> +      useFactory: (configService: ConfigService) => ({
Вот это можно вынести в папку config/typeOrm и там создать файл который вот эту вот функцию экспортит или же class (https://docs.nestjs.com/techniques/database#async-configuration)

2024-11-29 09:21 UTC, MishaShatilo commented on src/app.module.ts
> +    RedisModule.forRootAsync({
Тоже самое как с typeorm
@Injectable()
export class RedisConfigService implements RedisModuleOptionsFactory {
  constructor(private readonly configService: ConfigService<Config>) {}

  public createRedisModuleOptions():
    | RedisModuleOptions
    | Promise<RedisModuleOptions> {
    const { url } = this.configService.get<Config['redis']>('redis');

    return { config: { url } };
  }
}

2024-11-29 09:21 UTC, MishaShatilo commented on src/app.module.ts
> +    ConfigModule.forRoot({
Будет довольно таки полезно(https://docs.nestjs.com/techniques/configuration) + валидацию энвов можно сделать

2024-11-29 09:21 UTC, MishaShatilo commented on src/main.ts
> +
CORS надо настроить

2024-11-29 09:21 UTC, MishaShatilo commented on src/main.ts
> +  app.useGlobalPipes(
Давай еще exception filter добавим(https://docs.nestjs.com/exception-filters)

2024-11-29 09:21 UTC, MishaShatilo commented on src/migrations/1732713915708-addRolesAndUsers.ts
> +            (2, 'Jane', 'Smith', 'jane@smith.com', 'Password098!', 1);
В целом думаю в миграциях добавления ролей пока будет достаточно и пароль мы будем хешированный хранить

2024-11-29 09:21 UTC, MishaShatilo commented on src/migrations/1732714068407-addAnswers.ts
> +          (1, 'This is answer for question 1', 0, NOW(), NOW(), 1, 1),
В проде эти миграции заранятся которые добавляют тестовые данные поэтому их либо надо будет исключать либо переписать на сиды и функцию по добавлению сидов

2024-11-29 09:21 UTC, MishaShatilo commented on src/questions/dtos/create-question.dto.ts
> +  })
Поля эти сами будет сетать в базу нам не нужно их ожидать с фронта

2024-11-29 09:21 UTC, MishaShatilo commented on src/questions/dtos/create-question.dto.ts
> +  authorId: number;
Это будем с токена вытаскивать потом

2024-11-29 09:21 UTC, MishaShatilo commented on src/questions/providers/questions.service.ts
> +      author = await this.usersService.findOneById(createQuestionDto.authorId);
Promise all можем использовать

2024-11-29 09:21 UTC, MishaShatilo commented on src/questions/providers/questions.service.ts
> +    question.description = patchQuestionDto.description ?? question.description;
Можно через Object.assign()

2024-11-29 09:21 UTC, MishaShatilo commented on src/roles/role.entity.ts
> +  value: string;
Я бы enum сделал с ролями

2024-11-29 09:21 UTC, MishaShatilo commented on src/tags/providers/tags.service.ts
> +        id: In(tags),
Поидее если у тебя есть soft delete то надо тут проверку на него делать

2024-11-29 09:21 UTC, MishaShatilo commented on src/tags/tag.entity.ts
> +    onDelete: 'CASCADE',
Поидее это будет плохо работать с софт делитом, тоесть ты тег софт делитишь он помечается как удаленный, но в промежуточной таблице для many to many запись останется и нужно будет делать проверки

2024-11-29 09:21 UTC, MishaShatilo commented on src/tags/tag.entity.ts
> +@Entity()
сюда кстати название прокидывается

2024-11-29 09:21 UTC, MishaShatilo commented on src/users/providers/users.service.ts
> +      role = await this.rolesService.getRoleByValue('USER');
Можно юзера сразу с ролью доставать через join в случае typeorm relations

2024-11-29 09:21 UTC, MishaShatilo commented on tsconfig.json
> +  },
Думаю можем strict: true поставить

2024-12-04 13:46 UTC, AlekseyYuriev commented
Спасибо большое за обратную связь. Постарался учесть все рекомендации. Касательно документации для контроллеров (описание body, ошибки которые может вернуть эндпоинт и сам ответ который он будет возвращать): я пока что описал только questions controller. Если ты одобришь, то сделаю аналогично для остальных модулей. Также с методами в сервисах буду основательно работать после того, как настрою авторизацию. Заранее благодарю за ревью.

2024-12-05 08:42 UTC, merged